version: '3.3'

services:
      mysqldb:
            container_name: mysqldb
            image: mysql:5.7
            ports:
                  - "3310:3306"
            volumes:
                  -  ./mysqldb/:/var/lib/mysql
            restart: always
            environment:
                  MYSQL_ROOT_PASSWORD: root123
                  MYSQL_DATABASE: wpdb
                  MYSQL_USER: wpusr
                  MYSQL_PASSWORD: root123
            networks:
                  - wordpress-network
      wordpress:
            container_name: wordpress
            image: wordpress:latest
            volumes:
                  -  ./public/:/var/www/html
            environment:
                  WORDPRESS_DB_HOST: mysqldb:3306
                  WORDPRESS_DB_USER: wpusr
                  WORDPRESS_DB_PASSWORD: root123
                  WORDPRESS_DB_NAME: wpdb
            ports:
                  - "1000:80"
            links:
                  - mysqldb
            restart: always
            networks:
                  - wordpress-network
      phpmyadmin:
            container_name: phpmyadmin
            image: phpmyadmin/phpmyadmin:latest
            ports:
                  - "1001:80"
            links:
                  - mysqldb
            restart: always
            environment:
                  - PMA_ARBITRARY=1
                  - PMA_HOST=mysqldb
                  - MYSQL_ROOT_PASSWORD=root123
            volumes:
                  - /sessions1
            networks:
                  - wordpress-network
networks:
  wordpress-network:
      driver: bridge